---
title: "Incremental TikZ drawings"
author: "Günther Erhard"
date: last-modified
format: 
  revealjs:
    code-line-numbers: false
    theme: 
      - "./my-theme.scss"
---

## Test incremental TikZ drawings

Just a first proof of concept for incremental display of TikZ drawings in Quarto revealjs presentations ...

::: {.r-stack}
```{bash}
  quarto_tikz_increments.sh -f "./tikz-test.tikz" -i 0
```

```{r, cache = TRUE, echo = FALSE, engine = 'tikz', fig.ext = 'svg', engine.opts = list(dvisvgm.opts = "--font-format=woff", template = "./tikz-preamble.tex")}
#| fig-align: center
#| label: TikZ-Test
#| file: "./tikz-test-increments.tikz"
```

:::: {.fragment}
```{bash}
  quarto_tikz_increments.sh -f "./tikz-test.tikz" -i 1
```

```{r, cache = TRUE, echo = FALSE, engine = 'tikz', fig.ext = 'svg', engine.opts = list(dvisvgm.opts = "--font-format=woff", template = "./tikz-preamble.tex")}
#| fig-align: center
#| label: TikZ-Test-1
#| file: "./tikz-test-increments.tikz"
```
::::

:::: {.fragment}
```{bash}
  quarto_tikz_increments.sh -f "./tikz-test.tikz" -i 2 
```

```{r, cache = TRUE, echo = FALSE, engine = 'tikz', fig.ext = 'svg', engine.opts = list(dvisvgm.opts = "--font-format=woff", template = "./tikz-preamble.tex")}
#| fig-align: center
#| label: TikZ-Test-2
#| file: "./tikz-test-increments.tikz"
```
::::

:::: {.fragment}
```{bash}
  quarto_tikz_increments.sh -f "./tikz-test.tikz" -i 1 -i 3
```

```{r, cache = TRUE, echo = FALSE, engine = 'tikz', fig.ext = 'svg', engine.opts = list(dvisvgm.opts = "--font-format=woff", template = "./tikz-preamble.tex")}
#| fig-align: center
#| label: TikZ-Test-3
#| file: "./tikz-test-increments.tikz"
```
::::
:::

::: {.fragment}
**Now we are done!**
:::
